version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "org.cryptomator:integrations-api"
        versions: ["2.0.0-alpha1"]
      - dependency-name: "jakarta.inject:jakarta.inject-api"
        versions: ["2.0.1.MR"]
      - dependency-name: "org.openjfx:*"
      - dependency-name: "com.fasterxml.jackson.*"
        versions: [ "[2.22,)" ] # 2.21.x is LTS, see https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.21
    groups:
      maven-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/" # even for `.github/workflows`
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"