commit_message: "[ci skip]"
escape_special_characters: 0
files:
  - source: /src/main/resources/i18n/strings.properties
    translation: /src/main/resources/i18n/strings_%two_letters_code%.properties
