name: Feature Request
description: Suggest an idea for this project
labels: ["type:feature-request"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Please agree to the following
      options:
      - label: I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
        required: true
      - label: I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)
        required: true
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Please summarize your feature request.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Who requires this feature? What problem does the user face? How would this feature solve the problem?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Considered Alternatives
      description: What current alternatives or workarounds have you considered? Is there a different way to solve the same problem?
  - type: textarea
    id: context
    attributes:
      label: Anything else?
      description: Any context, suggestions, screenshots, or concepts you want to share?