name: Tmp Playground # committed on develop to make `workflow_dispatch` work. Will be removed, once PPA uploads work

on:
  workflow_dispatch:

jobs:

#
# DUMMY Metadata (TODO remove)
#
  metadata:
    name: Determine Dummy Version Metadata
    runs-on: ubuntu-latest
    outputs:
      versionStr: ${{ steps.versions.outputs.versionStr }}
      versionNum: ${{ steps.versions.outputs.versionNum }}
      revNum: ${{ steps.versions.outputs.revNum }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: versions
        run: |
          echo "::set-output name=versionStr::1.5.17"
          echo "::set-output name=versionNum::1.5.17"
          echo "::set-output name=revNum::`git rev-list --count HEAD`"

#
# Create and upload source package for ppa
#
  ppa:
    name: Upload source package to PPA
    needs: [metadata]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install build tools
        run: |
          sudo apt-get update
          sudo apt-get install debhelper devscripts dput
      - name: Download buildkit # TODO replace by downloading cached artifact
        run: |
          curl -o buildkit.zip -L https://github.com/cryptomator/cryptomator/releases/download/1.5.17/buildkit-linux.zip
          unzip buildkit.zip -d pkgdir
      - name: create orig.tar.gz
        run: >
          mk-origtargz
          --repack
          --package=cryptomator
          --version=${{ needs.metadata.outputs.versionNum }}.${{ needs.metadata.outputs.revNum }}
          buildkit.zip
      - name: patch and rename pkgdir
        run: |
          cp -r dist/linux/debian/ pkgdir
          export RFC2822_TIMESTAMP=`date --rfc-2822`
          envsubst '${VERSION_STR} ${VERSION_NUM} ${REVISION_NUM}' < dist/linux/debian/rules > pkgdir/debian/rules
          envsubst '${VERSION_STR}' < dist/linux/debian/org.cryptomator.Cryptomator.desktop > pkgdir/debian/org.cryptomator.Cryptomator.desktop
          envsubst '${PPA_VERSION} ${RFC2822_TIMESTAMP}' < dist/linux/debian/changelog > pkgdir/debian/changelog
          find . -name "*.jar" >> pkgdir/debian/source/include-binaries
          mv pkgdir cryptomator_${{ needs.metadata.outputs.versionNum }}.${{ needs.metadata.outputs.revNum }}
        env:
          VERSION_STR: ${{ needs.metadata.outputs.versionStr }}
          VERSION_NUM: ${{ needs.metadata.outputs.versionNum }}
          REVISION_NUM: ${{ needs.metadata.outputs.revNum }}
          PPA_VERSION: ${{ needs.metadata.outputs.versionNum }}.${{ needs.metadata.outputs.revNum }}-0ppa1
      - name: import gpg key 615D449FE6E6A235
        run: |
          echo "${GPG_PRIVATE_KEY}" | gpg --batch --quiet --import
          echo "${GPG_PASSPHRASE}" | gpg --batch --quiet --passphrase-fd 0 --pinentry-mode loopback -u 615D449FE6E6A235 --dry-run --sign dist/linux/debian/rules
        env:
          GPG_PRIVATE_KEY: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
      - name: debuild
        run: debuild -S -sa -d
        env:
          DEBSIGN_PROGRAM: gpg --batch --pinentry-mode loopback
          DEBSIGN_KEYID: 615D449FE6E6A235
        working-directory: cryptomator_${{ needs.metadata.outputs.versionNum }}.${{ needs.metadata.outputs.revNum }}
      - name: dput to beta repo
        run: dput ppa:sebastian-stenzel/cryptomator-beta cryptomator_${{ needs.metadata.outputs.versionNum }}.${{ needs.metadata.outputs.revNum }}_source.changes

