name: Publish  MSI to winget-pkgs

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true

permissions: {}

jobs:
  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Sync winget-pkgs fork
        run: |
          gh repo sync cryptomator/winget-pkgs -b master --force
        env:
          GH_TOKEN: ${{ secrets.CRYPTOBOT_PR_TOKEN }}
      - name: Submit package
        uses: vedantmgoyal2009/winget-releaser@b7370d4d152efdce803a26cc6ca9eee58cb2ad54 # no_specific_version
        with:
          identifier: Cryptomator.Cryptomator
          version: ${{ inputs.tag }}
          release-tag: ${{ inputs.tag }}
          installers-regex: '-x64\.msi$'
          token: ${{ secrets.CRYPTOBOT_PR_TOKEN }}